repos:
  - repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://github.com/pre-commit/pre-commit-hooks

    rev: v1.2.3
    hooks:
      - id: flake8
        args: [ '--ignore=E501' ]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.24.0
    hooks:
      - id: pyupgrade