AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.

Parameters:
  StageName:
    Type: String

Resources:


  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html
  DefaultApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: live
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: !Sub s3://cicd-bucket-eu-west-3/spec/api-spec.yaml

  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
  FindHelloMsgFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src.handler.find_hello_msg
      Runtime: python3.7
      # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref DefaultApi
            Path: /helloworld
            Method: GET
      Environment:
        Variables:
          TABLE_NAME: !Ref Table

  CreateHelloMsgFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src.handler.create_hello_msg
      Runtime: python3.7
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref DefaultApi
            Path: /helloworld
            Method: POST
      Environment:
        Variables:
          TABLE_NAME: !Ref Table

  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-simpletable.html
  # https://docs.aws.amazon.com/fr_fr/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "helloworld-${StageName}"
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: language
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: language
          AttributeType: S
        - AttributeName: uuid
          AttributeType: S
      GlobalSecondaryIndexes:
        - IndexName: uuid
          KeySchema:
            - AttributeName: uuid
              KeyType: HASH
          Projection:
            ProjectionType: ALL