AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:

  # An API definition for multiple serverless functions
  DefaultApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: develop
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: !Sub s3://cicd-bucket-eu-west-3/spec/api-spec.yaml

  CreateBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'bookshelf-create-book-fct'
      Handler: src.bookshelf.handler.create_book
      Runtime: python3.7
      Policies:
        - DynamoDBCrudPolicy:
            TableName: books
      Events:
        CreateBook:
          Type: Api
          Properties:
            RestApiId: !Ref DefaultApi
            Path: /books
            Method: POST

  DeleteBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'bookshelf-delete-book-fct'
      Handler: src.bookshelf.handler.delete_book
      Runtime: python3.7
      Policies:
        - DynamoDBCrudPolicy:
            TableName: books
      Events:
        CreateBook:
          Type: Api
          Properties:
            RestApiId: !Ref DefaultApi
            Path: /books/{book_index}
            Method: DELETE

  FindBooksFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'bookshelf-find-books-fct'
      Handler: src.bookshelf.handler.find_books
      Runtime: python3.7
      Policies:
        - DynamoDBCrudPolicy:
            TableName: books
      Events:
        CreateBook:
          Type: Api
          Properties:
            RestApiId: !Ref DefaultApi
            Path: /books
            Method: GET

  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: books
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: author
          KeyType: HASH
        - AttributeName: title
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: author
          AttributeType: S
        - AttributeName: title
          AttributeType: S
        - AttributeName: genre
          AttributeType: S
        - AttributeName: publication_date
          AttributeType: S
        - AttributeName: uuid
          AttributeType: S
      LocalSecondaryIndexes:
        - IndexName: author-genre
          KeySchema:
            - AttributeName: author
              KeyType: HASH
            - AttributeName: genre
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      GlobalSecondaryIndexes:
        - IndexName: genre-publication
          KeySchema:
            - AttributeName: genre
              KeyType: HASH
            - AttributeName: publication_date
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: uuid
          KeySchema:
            - AttributeName: uuid
              KeyType: HASH
          Projection:
            ProjectionType: ALL