openapi: "3.0.1"
info:
  version: "1"
  title: "Musiclibrary documentation"


servers:
  - url: "https://{api_id}.execute-api.eu-west-3.amazonaws.com/live"
    variables:
      api_id:
        default: api_id
        description: set api id

paths:

  /songs:
    post:
      summary: "Create a Musiclibrary"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/music"
      responses:
        201:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/music"
      security:
        - sigv4: [ ]
      x-amazon-apigateway-request-validator: validate_request
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: 201
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateSongFunction.Arn}/invocations"
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
  /songs/{uuid}:
    get:
      summary: "Find music in library by uuid"
      parameters:
        - in: path
          name: uuid
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/music"
      security:
        - sigv4: [ ]
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: 200
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FindSongFunction.Arn}/invocations"
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy

components:
  schemas:
    music:
      type: Array
      properties:
        songs:
          type: Object
          schema:
            $ref: "#/components/schemas/song"
    song:
      type: Object
      properties:
        title:
          type: String
        genre:
          type: String
        author:
          type: String
        date:
          type:String

securityDefinitions:
  sigv4:
    type: apiKey
    name: Authorization
    in: header
    x-amazon-apigateway-authtype: awsSigv4

x-amazon-apigateway-request-validators:
  validate_request:
    validateRequestBody: true
    validateRequestParameters: true